### ISSUE TITLE
RIP: $RAID Liquidity 

### ISSUE THREAD

**Issue by YalorMewn** [raid-guild/RIPs#54]
# Project Idea

Proposal to add liquidity for $RAID into an xDai DEX of the groups choice ( https://honeyswap.org/, https://swapr.eth.link/, etc ) 

### Project Submitted By

@YalorMewn 

## Summary

$RAID is **ALIVE** 👾 and it's in the hands of users, yet there is no liquidity and no volume for new clients to purchase. 

It is my belief that we should be the first into the pool to set the price and to activate the trading potential. I'm not opposed to *how* we do that, just that we allocate the funding from the DAO to make this possible. 

## Why should we build this?

If we *do* this, I think it will kickstart the utility of $RAID, get people more excited about the token, and potentially encourage others to follow us into the pools, thereby creating greater depths of liquidity. 

If we *don't* do this, I think it shows a lack of alignment between RaidGuild and the $RAID token. 

## Anything else you'd like to add?

This is the earliest version of the proposal, totally up for discussion and further refinement. 

## Raid Party Skills Needed

- Tokenomics
- Project Management 
- Price modeling, analysis, forecasting

## Cost (in USD)

$30,000 ~ (90% of the budget used directly for providing liquidity and 10% distributed to the group for managing the process)

**Comment by slgraham** [comment]
I completely agree! 

Two key questions we'll need to answer:

### 1. What token should we pair with RAID?
My recommendation would be to pair RAID with WETH. Why WETH? Because we should reserve our DAI for RIP funding, and I also like the idea that we can slightly hedge RAID value and WETH value.

### 2. What network should we use?

My recommendation at this point is to stick with xDAI. Our consultation queue is on xDAI, so that will minimize friction between buying and using RAID (imagine a buy option embedded directly into the consultation queue app).

While other networks (eg Polygon) have more liquidity, currently it is far from certain where the bulk of liquidity will end up living. We'll do best to be patient and allow L2s to proliferate before making a decision on which L2 (or sidechain) to embrace as a DAO.

**Comment by YalorMewn** [comment]
wETH <> RAID has my vote as well, xDai also seems to be the preferred choice of the DAO for many things so happy to stick with that. 

I wonder now that it's on my mind, if we would be wise to follow the footsteps of our comrade's over at DAOhaus and create an incentivized liquidity DAO ala POOLhaus ? 

We could use a portion of tokens from the treasury to provide rewards for LP's, we could also use the same logic that DAOhaus did and use the Swappr DEX, I think we have a strong enough community to get a decent sized pool up and running in a short period or time. 

I would like to consider adding this option as an expansion of the original scope. Would love a clear **YES** from the group before I start putting anything together though. 

I wonder if a DAO vote is in order ?

**Comment by youngkidwarrior** [comment]
@YalorMewn 

Yes, great call on opening $RAID to investors, and incentivizing LPs with the POOLHaus style seems  effective.

If I have a single sentiment input I'd say it is to use [Swapr](http://swapr.eth.link)! Swapr has a "make your own" LP rewards feature where you can set variables and time-frames for pools. DAOHaus and DxDao also have an active conversation about special rewards for [POOLHaus](https://daotalk.org/t/proposed-discussion-for-an-xdai-swapr-rewards-pool-for-haus-weth-pair-focused-around-the-novel-lpdao-poolhaus/3199), which may act as further benefit for RAID going this route.

**Comment by GoLOLO** [comment]
We def need to get $RAID into the hands of people who want to use it, which begs the question: What are our goals for $RAID?
- Satisfy any demand for the token i.e. incent liquidity?
- Drive token value?
- Fill RG Treasury for RIPs?

Are these the options we are looking at?

1) Liquidity DAO - I'm liking the liquidity DAO ala POOLHaus!
2) Traditional incentivized LP 
3) Token sale where we set the price

**Comment by ceresbzns** [comment]
Agree that xDai is probably the place to be. 

I'm not sure I agree that wETH-RAID is the optimal pair - I think we should at least discuss using a stable-RAID pair like wxDAI-RAID or RAI-RAID. 

What we choose depends on which side of the tradeoff we value more.  wETH-RAID will have, broadly, lower impermanent loss since I imagine our expectations are that ETH and RAID will both continue to increase in value. However, the volatility inherent in both tokens does mean that the total value of the liquidity pool will be volatile. 

A stable-RAID pair will at least provide significantly stability in the overall value of the liquidity pool held by the DAO, even as the price of RAID fluctuates. The long-term price paid for this stability is the IL incurred as RAID increases in valuation. This will be offset by the fact that arb bots will pay the LPs for the privilege of arbing the price, thanks to swap fees. 

For that reason, I'd favor a stable-RAID pair, but I don't have strong opinion on the matter.

I would also like to propose that we partner with Honeyswap. I have a high degree of confidence that we could get the Honeyswap team to offer LP incentive rewards for a RAID pair in exchange for some RAID or perhaps just a kindly worded letter.

**Comment by oovg** [comment]
+1 for RAID/RAI would be an epic pair
